--liquibase formatted sql

--changeset princeO:78888-createtablecontacts
CREATE TABLE contacts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(255)
    lastname VARCHAR(255)
);

--rollback drop table contacts;
